- include_vars: sys-vars.yml

- name: Clone Git docker repositories
  git:
    repo: "{{ item.url }}"
    dest: "/srv/JARVIS-IS/{{ item.name }}"
  with_items: "{{ dockers }}"

  become: true

- name: Clone Git nohup repositories
  git:
    repo: "{{ item.url }}"
    dest: "/srv/JARVIS-IS/{{ item.name }}"
  with_items: "{{ nohup }}"

  become: true
