- include_vars: sys-vars.yml

- name: Clone Git docker repositories
  git:
    repo: "https://github.com/JARVIS-IS/{{ item }}.git"
    dest: "/srv/JARVIS-IS/{{ item }}"
  with_items: "{{ dockers }}"
  become: true
