- name: Setup Server
  hosts: all
  gather_facts: no
  roles:
      - name: ../roles/setup
  tags:
      - setup

- name: Install Docker
  hosts: all
  gather_facts: no
  roles:
      - name: ../roles/docker
  tags:
      - sys
      - docker

- name: Setup SYS
  hosts: all
  gather_facts: no
  roles:
      - name: ../roles/sys-setup
  tags:
      - sys
