- include_vars: sys-vars.yml

- name: Clone Git repositories
  git:
    repo: "git@github.com:JARVIS-IS/{{ item }}.git"
    dest: "/srv/JARVIS-IS/{{ item }}"
    force: true
  with_items: "{{ dockers }}"
  become: true
